version: "3.9"
services:
  app:
    # command: "sleep 1000"
    # command: "poetry run python /src/test_project/funcs.py"
    build: .
    volumes:
      - ./src/test_project:/src/test_project
      # - ./src/test_project:/src/test_project
      # - ./entrypoint.sh:/entrypoint.sh
      # - ./poetry.lock:/app/poetry.lock
      # - ./pyproject.toml:/app/pyproject.toml
    ports:
      - "80:80"
    # entrypoint:
    #   /entrypoint.sh

    # poetry run uvicorn src.test_project.funcs:app --host 0.0.0.0 --port 80