version: "3.3"
services:
  app:
    build: .
    volumes:
      - ./src/test_project:/src/test_project
    ports:
      - "80:80"
    environment:
      - WATCHFILES_FORCE_POLLING=true
    # networks:
    #   - network1

  pgmaster:
    image: postgres:12
    environment:
      POSTGRES_DB: "dev"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./new_people.csv:/new_people.csv
      # - ./config/postgresql.conf:/var/lib/postgresql/data/master_postgresql.conf
    ports:
      - "5432:5432"


  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - 5672:5672
  #     - 15672:15672

  # tarantool:
  #   container_name: mytarantool
  #   image: tarantool/tarantool
  #   command: tarantool ../../usr/local/share/tarantool/app.init.lua
  #   ports:
  #     - 3301:3301
  #   volumes:
  #     - ./db/app.init.lua:/usr/local/share/tarantool/app.init.lua
  #     - ./new_people.csv:/new_people.csv
  #     - ./new_people1.csv:/new_people1.csv
  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - network1

  # prometheus:
  #   image: prom/prometheus
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   networks:
  #     - network1
    
  # postgres-exporter:
  #   image: prometheuscommunity/postgres-exporter
  #   ports:
  #     - 9187:9187
  #   environment:
  #     DATA_SOURCE_NAME: "postgresql://admin:admin@pgmaster:5432/dev?sslmode=disable"
  #   links:
  #     # - pgmaster
  #     - prometheus
  #   networks:
  #     - network1
  
# networks:
#   network1:
#     name: pgnet
#     external: true
  dialog_ms:
    build: ./dialog_ms
    volumes:
      - ./dialog_ms/src/dialog_ms:/src/dialog_ms
    ports:
      - "12345:12345"
    environment:
      - WATCHFILES_FORCE_POLLING=true
    # networks:
    #   - network1

  pg_dialog_ms:
    image: postgres:12
    environment:
      POSTGRES_DB: "dev"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./dialog_ms/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
